apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 10s
  ref:
    branch: main
  url: https://github.com/PhamMinhHiepIT2/flux-example.git
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 10s
  path: ./flux-system
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system 