apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../flux-system/gotk-components.yaml
  - ../../infrastructure/monitoring/namespace.yaml
  - ../../infrastructure/monitoring/prometheus.yaml
  - ../../infrastructure/monitoring/grafana.yaml
  - ../../apps/example-app/base/namespace.yaml
  - ../../apps/example-app/base/deployment.yaml 